#!/bin/bash

# Exit on any failure
set -e

echo "🔧 Installing Java 11 via Amazon Linux Extras..."
sudo amazon-linux-extras enable java-openjdk11
sudo yum clean metadata
sudo yum install -y java-11-openjdk java-11-openjdk-devel

echo " Java version:"
java -version

echo " Changing to /opt directory..."
cd /opt

echo " Downloading SonarQube 8.9.10..."
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.9.10.61524.zip

echo " Extracting SonarQube..."
sudo unzip sonarqube-8.9.10.61524.zip
sudo mv sonarqube-8.9.10.61524 sonarqube

echo " Creating sonar user..."
sudo adduser sonar

echo " Setting password for sonar user..."
echo "sonar:karthik111" | sudo chpasswd

echo " Setting ownership of /opt/sonarqube to sonar..."
sudo chown -R sonar:sonar /opt/sonarqube

echo " Updating RUN_AS_USER in sonar.sh..."
sudo sed -i 's/^#RUN_AS_USER=/RUN_AS_USER=sonar/' /opt/sonarqube/bin/linux-x86-64/sonar.sh

echo " Starting SonarQube as sonar user..."
sudo -u sonar /opt/sonarqube/bin/linux-x86-64/sonar.sh start

sleep 5

echo " Checking SonarQube status..."
sudo -u sonar /opt/sonarqube/bin/linux-x86-64/sonar.sh status

echo " SonarQube installation completed!"
echo " Access SonarQube at: http://<your-ec2-ip>:9000"
